name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  test:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libgtest-dev cmake doxygen graphviz python3
    
    - name: Build project
      run: |
        chmod +x scripts/build.sh
        ./scripts/build.sh
    
    - name: Run tests
      run: |
        chmod +x scripts/test.sh
        ./scripts/test.sh